name: IaC Checks

inputs:
  working_directory:
    description: The working directory to run IaC checks
    required: true

runs:
  using: composite
  steps:
    - name: Change directory
      run: cd ./${{ inputs.working_directory }}
      shell: bash

    - name: Initialize OpenTofu
      run: tofu init
      shell: bash

    - name: Validate OpenTofu formatting
      run: tofu fmt -check
      shell: bash

    - name: Validate OpenTofu configuration
      run: tofu validate
      shell: bash

    - name: Initialize tflint
      run: tflint --init
      shell: bash

    - name: Run tflint
      run: tflint -f compact
      shell: bash

    - name: Run checkov
      uses: bridgecrewio/checkov-action@v12
      with:
        framework: terraform
        download_external_modules: true
        directory: ./${{ inputs.working_directory }}
