name: IaC Checks

on:
  pull_request:
    paths: ["*.tf"]

jobs:
  iac-checks:
    name: IaC Checks
    uses: ehassett/workflows/.github/workflows/iac-checks.yaml@feature/add-iac-checks-workflow
    with:
      tool: "tofu"
