name: Generate terraform-docs

on:
  pull_request_target:
    types: [closed]

permissions:
  contents: write
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ github.token }}

jobs:
  terraform-docs:
    if: ${{ (github.event.pull_request.merged == true) }}
    name: Generate terraform-docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.base_ref }}

      - name: Run terraform-docs and push README
        uses: terraform-docs/gh-actions@v1.2.0
        with:
          config-file: .terraform-docs.yml
          git-push: "true"
          git-commit-message: "docs: update terraform-docs"
